spring.application.name=backend
# Connessione al Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gestore_giochi
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:Gestore_Giochi_postGres@}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:&MCS8rKy&fadeE6}

# Configurazione JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true