spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gestore_giochi}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:Gestore_Giochi_postGres@}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:&MCS8rKy&fadeE6}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=true